name: Update Rules
on:
  push:
  workflow_dispatch:

env:
  GITHUBTOKEN: ${{ secrets.GITHUBTOKEN }}

jobs:
  Pushed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Make Rules and Git push assets to github
        run: |
          bash ./make.sh
          git init
          git config --local user.name "action"
          git config --local user.email "action@github.com"
          git branch -m main
          git add --all
          git commit -m "Updated at $(TZ=UTC-8 date +'%Y-%m-%d %H:%M:%S')（北京时间）"
          git push --force -u origin          

      - name: Git push assets to other repos
        run: |
          rm -rf .git/
          git init          
          git config --local user.name "damengzhu"
          git config --local user.email "1985980570@qq.com"
          git remote add origin "https://damengzhu:${{ secrets.JIHU_TOKEN }}@jihulab.com/damengzhu/banad.git"
          git branch -m main          
          git add .
          git commit -am "Update at $(TZ=UTC-8 date +"%Y-%m-%d %H:%M")"
          git push --force -u main
          
      - name: Manual-Update AdRules Repository
        run: |
          bash ./manual-update.sh
